sudo: required
dist: bionic
language: c
python:
  - "3.6"
cache:
  apt: true
  directories:
  - /home/travis/postgresql
env:
  global:
    # GitHub API token for citus-bot
    - secure: degV+qb2xHiea7E2dGk/WLvmYjq4ZsBn6ZPko+YhRcNm2GRXRaU3FqMBIecPtsEEFYaL5GwCQq/CgBf9aQxgDQ+t2CrmtGTtI9AGAbVBl//amNeJOoLe6QvrDpSQX5pUxwDLCng8cvoQK7ZxGlNCzDKiu4Ep4DUWgQVpauJkQ9nHjtSMZvUqCoI9h1lBy9Mxh7YFfHPW2PAXCqpV4VlNiIYF84UKdX3MXKLy9Yt0JBSNTWLZFp/fFw2qNwzFvN94rF3ZvFSD7Wp6CIhT6R5/6k6Zx8YQIrjWhgm6OVy1osUA8X7W79h2ISPqKqMNVJkjJ+N8S4xuQU0kfejnQ74Ie/uJiHCmbW5W2TjpL1aU3FQpPsGwR8h0rSeHhJAJzd8Ma+z8vvnnQHDyvetPBB0WgA/VMQCu8uEutyfYw2hDmB2+l2dDwkViaI7R95bReAGrpd5uNqklAXuR7yOeArz0ZZpHV0aZHGcNBxznMaZExSVZ5DVPW38UPn7Kgse8BnOWeLgnA1hJVp6CmBCtu+hKYt+atBPgRbM8IUINnKKZf/Sk6HeJIJZs662jD8/X93vFi0ZtyV2jEKJpouWw8j4vrGGsaDzTEUcyJgDqZj7tPJptM2L5B3BcFJmkGj2HO3N+LGDarJrVBBSiEjhTgx4NnLiKZnUbMx547mCRg2akk2w=
matrix:
  fast_finish: true
  include:
    - env: PGVERSION=10 TEST=single
    - env: PGVERSION=11 TEST=single
    - env: PGVERSION=12 TEST=single
    - env: PGVERSION=13 TEST=single
    - env: PGVERSION=10 TEST=multi
    - env: PGVERSION=11 TEST=multi
    - env: PGVERSION=12 TEST=multi
    - env: PGVERSION=13 TEST=multi
    - env: LINTING=true
    - env: LINTING=false
before_install:
  - git clone -b v0.7.18 --depth 1 https://github.com/citusdata/tools.git
  - sudo make -C tools install
  - 'if [ -z "$LINTING" ]; then setup_apt; fi'
  - 'if [ -z "$LINTING" ]; then nuke_pg; fi'
  - python --version
  - pyenv versions
  - pyenv install -s 3.7
  - pyenv global 3.7
  - sudo apt-get install bridge-utils
  - sudo apt-get install python3-pip
  - sudo pip3 install --upgrade pip
  - pip3 install --user pipenv
  - pip3 install --user black
install:
  - 'if [ -n "$LINTING" ]; then install_uncrustify; fi'
  # cleanup uncrustify build files
  - 'if [ -n "$LINTING" ]; then rm -rf uncrustify*; fi'
  - 'if [ -z "$LINTING" ]; then install_pg; fi'
  - 'if [ -z "$LINTING" ]; then install_custom_pg; fi'
  - PIPENV_PIPFILE="${TRAVIS_BUILD_DIR}"/tests/Pipfile pipenv install --system --deploy
  - env
  - 'if [ -z "$LINTING" ]; then pg_config; fi'
  - 'if [ -z "$LINTING" ]; then PATH=`pg_config --bindir`:$PATH which pg_ctl; fi'
script:
  - 'if [ -n "$LINTING" ]; then citus_indent --check; fi'
  - 'if [ -n "$LINTING" ]; then black --check .; fi'
  - 'if [ -n "$LINTING" ]; then ci/banned.h.sh; fi'
  - 'if [ -z "$LINTING" ]; then make -j5 CFLAGS=-Werror; fi'
  - 'if [ -z "$LINTING" ]; then sudo make install; fi'
  - 'if [ -z "$LINTING" ]; then PATH=`pg_config --bindir`:$PATH make test; fi'
